spring:
  datasource:
    url: jdbc:mysql://localhost:3306/twitterclone
    username: root
    password: yd7VafXJ
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect